# https://yunohost.org/en/packaging_manifest
packaging_format = 2

id = "zigbee2mqtt"
name = "Zigbee2MQTT"
description.en = "Zigbee2MQTT as YunoHost package"

version = "1.42.0~ynh1"

maintainers = ["Jens Diemer"]

[upstream]
license = "GPL-3.0-or-later"
admindoc = "https://github.com/YunoHost-Apps/zigbee2mqtt_ynh"
userdoc = "https://github.com/Koenkk/zigbee2mqtt"
code = "https://github.com/YunoHost-Apps/zigbee2mqtt_ynh"

[integration]
yunohost = ">=12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"

    [install.admin]
    type = "user"
    default = "admin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.serial_port]
    ask.en = "Serial port of our Zigbee adapter"
    type = "string"
    example = "/dev/serial/by-id/your-CC2652RB_usb_stick_id"
    default = "/dev/ttyUSB0"
    help.en = "See also: https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html - Use 'ls /dev/serial/by-id/*' to find the correct serial port."

[resources]
    [resources.sources.main]
    url = "https://github.com/Koenkk/zigbee2mqtt/archive/refs/tags/1.42.0.tar.gz"
    sha256 = "8bdc6e3570241b4c9a5b676396456b3845b66040844a80084bc456f7a774c1dd"
    autoupdate.strategy = "latest_github_tag"
    prefetch = true

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
