#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# NODE ENVIRONMENT
#=================================================
ynh_script_progression "Create and setup environment..."

ynh_setup_source --dest_dir="$install_dir"

touch /dev/ttyUSB0

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="configuration.yml" --destination="$install_dir/configuration.yml"

#chmod 400 "$install_dir/configuration.yml"
#chown "$app:$app" "$install_dir/configuration.yml"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Zigbee to MQTT bridge" --log="/var/log/$app/$app.log"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing $app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm --version
	ynh_hide_warnings ynh_exec_as_app npm ci
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
