#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD RESTORATION STEPS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Restoring the NGINX web server configuration..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring $app  main directory..."

ynh_restore "$install_dir"

ynh_script_progression "Set file permissions..."
myynh_fix_file_permissions

#=================================================
# NODE ENVIRONMENT
# Maybe the backup contains a other Python version
#=================================================
ynh_script_progression "Create and setup environment..."

myynh_setup_node_environment

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring the systemd $app configuration..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Set file permissions..."
myynh_fix_file_permissions

#=================================================
# START PYINVENTORY
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

ynh_systemctl --service=$app --action="start"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression "Reloading nginx web server..."

ynh_systemctl --service="nginx" --action="reload"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Restoration completed for $app"
