#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping systemd service '$app'..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# NODE ENVIRONMENT
#=================================================
ynh_script_progression "Create and setup environment..."

# Download, check integrity, uncompress "[resources.sources.main]" archive:
ynh_setup_source --dest_dir="$install_dir"

myynh_setup_node_environment

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring systemd service '$app'..."

ynh_config_add_systemd

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Set file permissions..."
myynh_fix_file_permissions

#=================================================
# Start the app server via systemd
#=================================================
ynh_script_progression "Starting systemd service '$app'..."

yunohost service add $app
ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
